server:
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/demo
    username: demo
    password: demo

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cache:
    type: caffeine
